id: P000356
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 2021-12-16 15:35:40.581546
source_metadata:
  id: bdr:W29106
  title: ཕྱི་རྒྱུད་ཀྱི་འགྲེལ་པ་མུན་སེལ་སྒྲོན་མེ
  author: ''
  volumes:
    fa2001332f194f9281534b7d75c4e206:
      image_group_id: I1PD388
      title: Volume 1 of phyi rgyud kyi 'grel pa mun sel sgron me
      volume_number: 1
      total_pages: 240
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
